# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Boalaroid
tagline:          'We make amazing video'
description:      'Lorem Ipsum'
url:              http://www.boalaroid.co.uk
baseurl:          /

author:
  name:           'Dale Valentine'
  url:            https://twitter.com/Hartz_69

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/boalaroid/www
